files_unchanged:
# FIXME remove after tools:dsl2_template has been merged
  - lib/NfcoreSchema.groovy
# FIXME CI currently runs for dev and dsl2 branches, remove the latter before merging to dev
actions_ci: False
files_exist:
  - bin/markdown_to_html.py
