sudo: required

language: java

jdk: openjdk8

services:
  - docker

install:
  - mkdir /tmp/nextflow
  - cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  - cd ${TRAVIS_BUILD_DIR}/tests/

script:
  - "./docker_test.sh"        # Basic run
  - "./docker_test.sh -b"     # Run, build reference genome
  - "./docker_test.sh -r"     # Run, RRBS mode
  - "./docker_test.sh -n"     # Run, no-trimming mode
  - "./docker_test.sh -p"     # BWAmeth use existing ref genome
  - "./docker_test.sh -p -b"  # BWAmeth run, build reference genome
