sudo: required

language: java

jdk: openjdk8

services:
  - docker
install:
  - mkdir /tmp/nextflow
  - cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  - cd ${TRAVIS_BUILD_DIR}/tests/
  - mkdir results

env:
  - s=docker_test
  - s=docker_test_bwameth

script:
  - "./${s}.sh"
  - "./${s}.sh true" # Run again, building reference genome
