sudo: required

language: java

jdk: openjdk8

services:
  - docker

install:
  - mkdir /tmp/nextflow
  - cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  - cd ${TRAVIS_BUILD_DIR}/tests/

env:
  - CLFLAGS=""       # Basic run
  - CLFLAGS="-b"     # Run, build reference genome
  - CLFLAGS="-r"     # Run, RRBS mode
  - CLFLAGS="-n"     # Run, no-trimming mode
  # Commented out until I figure out how to handle multiple docker images nicely
  # - CLFLAGS="-p"     # BWAmeth use existing ref genome
  # - CLFLAGS="-p -b"  # BWAmeth run, build reference genome

script:
  - "./run_test.sh $CLFLAGS"
