# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-methylseq-1.4.1dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # nf-core dependencies
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - bioconda::fastqc=0.11.8
  # Default bismark pipeline
  - bioconda::trim-galore=0.6.5
  - bioconda::samtools=1.9
  - bioconda::bowtie2=2.3.5
  - bioconda::hisat2=2.1.0
  - bioconda::bismark=0.22.3
  - bioconda::qualimap=2.2.2d
  - bioconda::preseq=2.0.3
  - bioconda::multiqc=1.8
  # bwa-meth pipeline
  - bioconda::picard=2.21.4
  - bioconda::bwameth=0.2.2
  - bioconda::methyldackel=0.4.0

