name: conda CI

on:
  pull_request:
    # run only if environment.yml changed
    paths:
      - 'environment.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: docker://continuumio/miniconda3:4.8.2
      - name: Build conda environment
        run: conda env create -f ${GITHUB_WORKSPACE}/environment.yml